### ISSUE TITLE
64-bit Support

### ISSUE THREAD

**Issue by hezhao** [pizthewiz/Cinder-EDSDK#2]
although EDSDK is not x86_64 compatible, its provided 64 bit library actually works fine with your code. I was able to trigger the shutter and transfer the photo to the computer.

**Comment by pizthewiz** [comment]
Yeah, the EDSDK for OS X has an `x86_64` slice in _EDSDK.framework_ but only an `i386` slice in _DPP.framework_ - roughly, I believe _EDSDK.framework_ handles camera connection and _DPP.framework_ handles image specific stuff.

Is it possible Cinder-EDSDK doesn't use any functionality from _DPP.framework_? If so, we could build `x86_64`! Thanks for bringing this up!

**Comment by pizthewiz** [comment]
Sure enough, it looks like Cinder-EDSDK isn't using anything out of _DPP.framework_. Annoyingly the 64-bit version of _EDSDK.framework_ only has an `x86_64` slice, it isn't fat…

**Comment by pizthewiz** [comment]
Yup this is totally doable, thanks for bringing this up!

**Comment by hezhao** [comment]
according to the API document, `DPP.framework`, contains `MLib.bundle`, `￼￼UCS32.bundle` and ￼Resources Folder `￼￼xxx.icc`, I never knew what they are and it seems it works fine without this framework.

It's great that 64-bit `EDSDK.framework` works so that I don't have to compile everything else in 32-bit. Now running EDSDK 64-bit in my [camera calibration software](https://github.com/hezhao/Calibrator).

**Comment by pizthewiz** [comment]
The `x86_64` version of the framework seems to work pretty well for me, the only hangup I have run into is related to code signing and I'm not sure it is related. 64-bit changes merged in c627d81.

Calibrator is a pretty neat calibration tool, I am going to have to try it out! I took a workshop with Elliot Woods last summer that also offered some automatic calibration, check out [elliotwoods/ofxDigitalEmulsion](https://github.com/elliotwoods/ofxDigitalEmulsion).
